[package]
name = "rustIndex"
version = "0.1.0"
edition = "2021"

[[test]]
name = "main_test"
path = "src/main_test.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]